name: Selenium Automation Framework

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  selenium-test:

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Maven
        run: mvn -version

      - name: Execute Tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Report
          path: target/site/allure-maven-plugin

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber-Report
          path: target/cucumber-report.html
          if-no-files-found: warn

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Extent-Report
          path: target/extent-report
          if-no-files-found: warn

      - name: Upload Automation Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Logs & Screenshots
          path: |
            screenshots/
            logs/
          if-no-files-found: warn